//
//  MockData.swift
//  Itribez_iOS
//
//  Created by Indu Pandey on 08/08/23.
//

import Foundation

struct MockData {
    var activity: [NotificationModel] = [
        NotificationModel(activity: .liked,
                          duration: "15m",
                          usersInContext: [User(userName: "cristiano", userImage: "user_8"), User(userName: "neymarjr", userImage: "user_7")],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked")),
        NotificationModel(activity: .newFollower,
                          duration: "18h",
                          usersInContext: [User(userName: "rock'n_roll", userImage: "user_14")],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked"),
                          comment: ""),
        NotificationModel(activity: .liked,
                          duration: "5h",
                          usersInContext: [User(userName: "axeyked", userImage: "user_2"), User(userName: "neymarjr", userImage: "user_7")],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked")),
        NotificationModel(activity: .comment,
                          duration: "5h",
                          usersInContext: [User(userName: "zendaya", userImage: "user_9")],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked"),
                          comment: "@pankajgaikar ❤️🙏🏻"),
        NotificationModel(activity: .suggestFollower,
                          duration: "6h",
                          usersInContext: [User(userName: "abhijit_007", userImage: "user_17")],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked"),
                          comment: ""),
        NotificationModel(activity: .liked,
                          duration: "46m",
                          usersInContext: [User(userName: "abhishekkgadge", userImage: "user_1"), User(userName: "axeyked", userImage: "user_2") ],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked")),
        NotificationModel(activity: .liked,
                          duration: "46m",
                          usersInContext: [User(userName: "sherlock", userImage: "user_20"), User(userName: "john_watson", userImage: "user_8") ],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked")),
        NotificationModel(activity: .suggestFollower,
                          duration: "6h",
                          usersInContext: [User(userName: "hiker.benn", userImage: "user_18")],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked"),
                          comment: ""),
        NotificationModel(activity: .newFollower,
                          duration: "8h",
                          usersInContext: [User(userName: "abasu63", userImage: "user_19")],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked"),
                          comment: ""),
        NotificationModel(activity: .liked,
                          duration: "46m",
                          usersInContext: [User(userName: "harry_potter", userImage: "user_9"), User(userName: "john_wisley", userImage: "user_16") ],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked")),
        NotificationModel(activity: .newFollower,
                          duration: "18h",
                          usersInContext: [User(userName: "power_of_shiva_99", userImage: "user_20")],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked"),
                          comment: ""),
        NotificationModel(activity: .liked,
                          duration: "15m",
                          usersInContext: [User(userName: "cristiano", userImage: "user_8"), User(userName: "neymarjr", userImage: "user_7")],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked")),
        NotificationModel(activity: .newFollower,
                          duration: "18h",
                          usersInContext: [User(userName: "rock'n_roll", userImage: "user_14")],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked"),
                          comment: ""),
        NotificationModel(activity: .liked,
                          duration: "5h",
                          usersInContext: [User(userName: "axeyked", userImage: "user_2"), User(userName: "neymarjr", userImage: "user_7")],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked")),
        NotificationModel(activity: .comment,
                          duration: "5h",
                          usersInContext: [User(userName: "zendaya", userImage: "user_9")],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked"),
                          comment: "@pankajgaikar ❤️🙏🏻"),
        NotificationModel(activity: .suggestFollower,
                          duration: "6h",
                          usersInContext: [User(userName: "abhijit_007", userImage: "user_17")],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked"),
                          comment: ""),
        NotificationModel(activity: .liked,
                          duration: "46m",
                          usersInContext: [User(userName: "abhishekkgadge", userImage: "user_1"), User(userName: "axeyked", userImage: "user_2") ],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked")),
        NotificationModel(activity: .liked,
                          duration: "46m",
                          usersInContext: [User(userName: "sherlock", userImage: "user_20"), User(userName: "john_watson", userImage: "user_8") ],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked")),
        NotificationModel(activity: .suggestFollower,
                          duration: "6h",
                          usersInContext: [User(userName: "hiker.benn", userImage: "user_18")],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked"),
                          comment: ""),
        NotificationModel(activity: .newFollower,
                          duration: "8h",
                          usersInContext: [User(userName: "abasu63", userImage: "user_19")],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked"),
                          comment: ""),
        NotificationModel(activity: .liked,
                          duration: "46m",
                          usersInContext: [User(userName: "harry_potter", userImage: "user_9"), User(userName: "john_wisley", userImage: "user_16") ],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked")),
        NotificationModel(activity: .newFollower,
                          duration: "18h",
                          usersInContext: [User(userName: "power_of_shiva_99", userImage: "user_20")],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked"),
                          comment: ""),
        NotificationModel(activity: .liked,
                          duration: "15m",
                          usersInContext: [User(userName: "cristiano", userImage: "user_8"), User(userName: "neymarjr", userImage: "user_7")],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked")),
        NotificationModel(activity: .newFollower,
                          duration: "18h",
                          usersInContext: [User(userName: "rock'n_roll", userImage: "user_14")],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked"),
                          comment: ""),
        NotificationModel(activity: .liked,
                          duration: "5h",
                          usersInContext: [User(userName: "axeyked", userImage: "user_2"), User(userName: "neymarjr", userImage: "user_7")],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked")),
        NotificationModel(activity: .comment,
                          duration: "5h",
                          usersInContext: [User(userName: "zendaya", userImage: "user_9")],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked"),
                          comment: "@pankajgaikar ❤️🙏🏻"),
        NotificationModel(activity: .suggestFollower,
                          duration: "6h",
                          usersInContext: [User(userName: "abhijit_007", userImage: "user_17")],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked"),
                          comment: ""),
        NotificationModel(activity: .liked,
                          duration: "46m",
                          usersInContext: [User(userName: "abhishekkgadge", userImage: "user_1"), User(userName: "axeyked", userImage: "user_2") ],
                          post: Post(user: User(userName: "pankajgaikar", userImage: "user_16"), postImage: "post_18", caption: "If any one attempts to haul down the American flag, shoot him on the spot.", likes: "leomessi and others liked")),
    ]
    
}
